name: Build and Export

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching tags, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and Export
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:css

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts
          path: |
            dist/**
            !dist/styjes.js
          retention-days: 5
